name: C/C++ CI of aricpp

on: [push,pull_request]

jobs:
  build-ubuntu-gcc:
    name: Ubuntu gcc
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get install \
            libboost-dev libboost-thread-dev libboost-program-options-dev \
            libboost-system-dev
    - name: Build with GCC
      run: |
        cd samples
        g++ --version
        CC=gcc CXX=g++ make

  build-ubuntu-clang:
    name: Ubuntu clang
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get install \
            libboost-dev libboost-thread-dev libboost-program-options-dev \
            libboost-system-dev
    - name: Build with Clang
      run: |
        cd samples
        g++ --version
        CC=clang CXX=clang++ make

  build-macos-gcc:
    name: macOS gcc
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dependencies
      run: brew update && brew install boost
    - name: Build with GCC
      run: |
        cd samples
        g++ --version
        CC=gcc-10 CXX=g++-10 make

  build-macos-clang:
    name: macOS Clang
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dependencies
      run: brew update && brew install boost
    - name: Build with Clang
      run: |
        cd samples
        clang++ --version
        CC=clang CXX=clang++ make
